### ISSUE TITLE
“A list looks like a link.”

### ISSUE THREAD

**Issue by rosetree** [honza/honza.github.com#1]
Let me quote from your last post about markdown editors:

> A heading looks like a heading. A list looks like a link.

Maybe I don’t get the joke, but I don’t think it’s positive if **a list looks like a link** … Anyway, good article!

**Comment by honza** [comment]
Blech, thanks! :sparkles: 

Fixed now. Thanks for taking the time to look up this repo and report it :)

**Comment by rosetree** [comment]
Well, thank you for an open source blog and the quick fix. And the time for looking up my twitter account and so on ☺
